=== Raulms29/SEW/xml/rutas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified"
	targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="rutas">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="ruta" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ruta">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element ref="duracion" />
				<xs:element ref="recomendacion"  />
				<xs:element ref="hora_inicio" minOccurs="0" maxOccurs="1" />
				<xs:element ref="fecha_inicio" minOccurs="0" maxOccurs="1" />
				<xs:element ref="descripcion"  />
				<xs:element ref="coordenadas"  />
				<xs:element ref="referencias"  />
				<xs:element ref="hitos" />
			</xs:sequence>
			<xs:attribute name="nombre" type="xs:string" use="required" />
			<xs:attribute name="tipo" type="xs:string" use="required" />
			<xs:attribute name="medio_transporte" type="xs:string" use="required" />
			<xs:attribute name="agencia" type="xs:string" use="required" />
			<xs:attribute name="personas_adecuadas" type="xs:string" use="required" />
			<xs:attribute name="lugar_inicio" type="xs:string" use="required" />
			<xs:attribute name="direccion" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="duracion" type="xs:duration"></xs:element>
	<xs:element name="recomendacion">
		<xs:simpleType>
			<xs:restriction base="xs:decimal">
				<xs:fractionDigits value="2"/>
				<xs:minInclusive value="0.00" />
				<xs:maxInclusive value="10.00" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="hora_inicio" type="xs:time"></xs:element>
	<xs:element name="fecha_inicio" type="xs:date"></xs:element>
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="latitud" />
				<xs:element ref="longitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud" >
	<xs:simpleType>
			<xs:restriction base="xs:double">
			<xs:minInclusive value="-180.0" />	
			<xs:maxInclusive value="180.0" />	
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="latitud" >
		<xs:simpleType>
			<xs:restriction base="xs:double">
			<xs:minInclusive value="-90.0" />	
			<xs:maxInclusive value="90.0" />	
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:double">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="descripcion" type="xs:string" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:anyURI" />
	<xs:element name="hitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="hito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="hito">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element ref="coordenadas" />
				<xs:element ref="distancia" />
				<xs:element ref="galeria_fotos" />
				<xs:element minOccurs="0" maxOccurs="1" ref="galeria_videos" />
			</xs:sequence>
			<xs:attribute name="nombre" type="xs:string" use="required" />
			<xs:attribute name="descripcion" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:double">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="galeria_fotos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="fotografia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="galeria_videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="video" />
				<xs:element minOccurs="0" maxOccurs="2" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:anyURI" />
	<xs:element name="fotografia" type="xs:anyURI" />
</xs:schema>

=== Raulms29/SEW/xml/rutasEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>


<rutas
    xmlns="http://www.uniovi.es"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.uniovi.es rutas.xsd"
>
    <ruta nombre="Horton Plains" tipo="Senderismo" medio_transporte="A pie"
        agencia="Sin agencia"
        personas_adecuadas="Se puede ir con niños acostumbrados a caminar"
        lugar_inicio="Oficina del Parque Horton Plains" direccion="Parque Nacional Horton Plains"
    >
        <duracion>
            PT4H
        </duracion>
        <recomendacion>
            8
        </recomendacion>
        <hora_inicio>
            07:00:00
        </hora_inicio>
        <fecha_inicio>
            2018-08-03
        </fecha_inicio>
        <descripcion> Caminata por el parque nacional de Horton Plains [llanuras de Horton], en Sri
            Lanka, una planicie a 2.000 metros de altitud que acercan al caminante al Fin del Mundo
            (World's End), un mirador que cae a cuchillo 850 metros, para llevarlo luego a las
            cascadas Baker (Baker's falls), siempre entre parajes hermosos que combinan pequeños
            tramos de bosques con páramos acolinados poblados de azaleas. </descripcion>
        <coordenadas>
            <latitud>6.7668</latitud>
            <longitud>80.81045277777777</longitud>
            <altitud unidades="m">1938</altitud>
        </coordenadas>
        <referencias>
            <referencia>https://es.wikiloc.com/rutas-senderismo/horton-plains-sri-lanka-27187807</referencia>
            <referencia>https://es.wikipedia.org/wiki/Parque_nacional_de_las_Llanuras_de_Horton</referencia>
            <referencia>https://en.wikipedia.org/wiki/Baker%27s_Falls</referencia>
        </referencias>
        <hitos>
            <hito nombre="Mini Mirador del Fin del Mundo"
                descripcion="Mirador desde el que ya se contemplan unas maravillosas vistas del valle que forma, abajo, el río Kiriketi.">
                <coordenadas>
                    <latitud>6.7853083</latitud>
                    <longitud>80.80026388888889</longitud>
                    <altitud unidades="m">2122</altitud>
                </coordenadas>
                <distancia unidades="km">2.35</distancia>
                <galeria_fotos>
                    <fotografia>mini_fin_del_mundo</fotografia>
                </galeria_fotos>
            </hito>
            <hito nombre="Mirador del Fin del Mundo"
                descripcion="Acantilado de 870 metros de altura con vistas espectaculares">
                <coordenadas>
                    <latitud>6.78075</latitud>
                    <longitud>80.79449694444445</longitud>
                    <altitud unidades="m">2120</altitud>
                </coordenadas>
                <distancia unidades="km">1.3</distancia>
                <galeria_fotos>
                    <fotografia>fin_del_mundo</fotografia>
                </galeria_fotos>
            </hito>
            <hito nombre="Cascadas de Baker"
                descripcion="Cascada de 20 metros que obtuvo su nombre del explorador britanico Sir Samuel Baker">
                <coordenadas>
                    <latitud>6.7927194</latitud>
                    <longitud>80.78946666666667</longitud>
                    <altitud unidades="m">2085</altitud>
                </coordenadas>
                <distancia unidades="km">2.1</distancia>
                <galeria_fotos>
                    <fotografia>baker_falls</fotografia>
                </galeria_fotos>
            </hito>
        </hitos>
    </ruta>

    <ruta nombre="Ella - Little Adam's Peak - Nine Arches Bridge" tipo="Caminata"
        medio_transporte="A pie" agencia="Sin Agencia"
        personas_adecuadas="Adecuado para la mayoría" lugar_inicio="Ella"
        direccion="Ella Main Street">
        <duracion>
            PT6H30M
        </duracion>
        <recomendacion>
            7
        </recomendacion>
        <descripcion>Ruta circular preciosa. Un recorrido sencillo, muy bonito y con el que podemos
            visitar Little Adam's Peak y Nine Arches Bridge, dos de los puntos más interesantes de
            la zona. </descripcion>
        <coordenadas>
            <latitud>6.8727028</latitud>
            <longitud>81.04842222222221</longitud>
            <altitud unidades="m">1027</altitud>
        </coordenadas>
        <referencias>
            <referencia>
                https://es.wikiloc.com/rutas-senderismo/ella-little-adams-peak-1-146-m-nine-arches-bridge-40847339</referencia>
            <referencia>
                https://www.holidify.com/places/ella/main-street--sightseeing-1264874.html#:~:text=The%20Main%20Street%20at%20Ella,waiting%20to%20pick%20up%20passengers.</referencia>
            <referencia>
                https://en.wikipedia.org/wiki/Ella,_Sri_Lanka#/media/File:SL_Ella_asv2020-01_img22_View_from_Little_Adams_Peak.jpg</referencia>
            <referencia>https://en.wikipedia.org/wiki/Nine_Arch_Bridge</referencia>
        </referencias>
        <hitos>
            <hito nombre="Calle principal de Ella"
                descripcion="Una calle con multiples bares y restaurantes. Los restaurantes ofrecen vistas a la calle, normalmente repleta de tuk-tuks esperando para recoger pasajeros.">
                <coordenadas>
                    <latitud>6.8741278</latitud>
                    <longitud>81.04866666666666</longitud>
                    <altitud unidades="m">1013</altitud>
                </coordenadas>
                <distancia unidades="km">0.16</distancia>
                <galeria_fotos>
                    <fotografia> ella_main_street </fotografia>
                </galeria_fotos>
            </hito>
            <hito nombre="Little Adam's Peak"
                descripcion="Una modesta cumbre a 1146m que tiene unas vistas de escándalo hacia Ella y el entorno que nos rodea">
                <coordenadas>
                    <latitud>6.865125</latitud>
                    <longitud>81.06308055555556</longitud>
                    <altitud unidades="m">1127</altitud>
                </coordenadas>
                <distancia unidades="km">2.7</distancia>
                <galeria_fotos>
                    <fotografia> little_adams_peak </fotografia>
                </galeria_fotos>
            </hito>
            <hito nombre="Nine Arches Bridge"
                descripcion="Famoso puente reconocible por sus nueve arcos. Es uno de los mejores ejemplos de contrucción ferroviaria de la época colonial del país">
                <coordenadas>
                    <latitud>6.8767639</latitud>
                    <longitud>81.0608861111111</longitud>
                    <altitud unidades="m">958</altitud>
                </coordenadas>
                <distancia unidades="km">3.1</distancia>
                <galeria_fotos>
                    <fotografia> nine_arches_bridge </fotografia>
                </galeria_fotos>
            </hito>
        </hitos>
    </ruta>

    <ruta nombre="Sigiriya" tipo="Mountain Bike" medio_transporte="Bicicleta de Montaña"
        agencia="Sin agencia" personas_adecuadas="Personas en buena forma física"
        lugar_inicio="Sigiriya" direccion="Inamaluwa">
        <duracion>PT6H</duracion>
        <recomendacion>9</recomendacion>
        <descripcion>Ruta en bicicleta que va a Pirudangala Rock, un lugar con vistas fantásticas a
            Sigiriya Rock. Posteriormente visitamos el Museo de Sigiriya. Después iremos hasta
            Sigiriya Rock donde encontraremos los restos de un antiguo palacio, para finalmente
            volver al punto de partida</descripcion>
        <coordenadas>
            <latitud>7.9476278</latitud>
            <longitud>80.75220555555556</longitud>
            <altitud unidades="m">201</altitud>
        </coordenadas>
        <referencias>
            <referencia>
                https://es.wikiloc.com/rutas-mountain-bike/sigiriya-pidurangala-rock-lion-rock-sigiriya-22300983
            </referencia>
            <referencia>https://es.wikipedia.org/wiki/Sigiriya</referencia>
            <referencia>https://www.lovesrilanka.org/sigiriya-museum/</referencia>
        </referencias>
        <hitos>
            <hito nombre="Pirudangala Rock"
                descripcion="Zona de senderismo y escalada moderados hasta la cima de una roca, popular por sus vistas panorámicas.">
                <coordenadas>
                    <latitud>7.9661111</latitud>
                    <longitud>80.76184166666667</longitud>
                    <altitud unidades="m">320</altitud>
                </coordenadas>
                <distancia unidades="km">2.32</distancia>
                <galeria_fotos>
                    <fotografia> pirudangala_rock </fotografia>
                </galeria_fotos>
            </hito>
            <hito nombre="Museo de Sigiriya"
                descripcion="Establecido en 2009, el museo contiene galerías que muestran los esfuerzos de excavación llevados a cabo en Sigiriya.">
                <coordenadas>
                    <latitud>7.9570583</latitud>
                    <longitud>80.75195</longitud>
                    <altitud unidades="m">199</altitud>
                </coordenadas>
                <distancia unidades="km">4.3</distancia>
                <galeria_fotos>
                    <fotografia> sigiriya_museum </fotografia>
                </galeria_fotos>
            </hito>
            <hito nombre="Sigiriya Rock"
                descripcion="En la cima de la roca hay un palacio, además de la Puerta del León y el muro de los espejos.">
                <coordenadas>
                    <latitud>7.9569333</latitud>
                    <longitud>80.75994722222222</longitud>
                    <altitud unidades="m">349</altitud>
